"use client";

import { motion } from "framer-motion";
import { Card } from "@/components/ui/card";
import { Layers, Sparkles, Target, Zap, Users, Trophy } from "lucide-react";

const features = [
  {
    icon: Layers,
    title: "First Principles",
    description:
      "Break down complex concepts into fundamental truths. Build understanding from the ground up.",
  },
  {
    icon: Sparkles,
    title: "Motion Design",
    description:
      "Interactive animations that make invisible code execution visible and intuitive.",
  },
  {
    icon: Target,
    title: "AI Challenges",
    description:
      "Personalized coding projects generated by AI based on your interests and skill level.",
  },
  {
    icon: Zap,
    title: "Instant Feedback",
    description:
      "Real-time code execution and visualization so you learn by doing, not just reading.",
  },
  {
    icon: Users,
    title: "Community",
    description:
      "Share your projects, get feedback, and learn from other developers on the same journey.",
  },
  {
    icon: Trophy,
    title: "Progress Tracking",
    description:
      "Earn badges, track milestones, and build a portfolio of standout projects.",
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export function FeaturesSection() {
  return (
    <section className="py-24 px-4">
      <div className="mx-auto max-w-6xl">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-5xl font-bold mb-4">
            Why <span className="text-gradient-primary">FirstCode Forge</span>?
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            A revolutionary approach to learning code that combines deep
            understanding with engaging interactivity.
          </p>
        </motion.div>

        {/* Features Grid */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          className="grid md:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          {features.map((feature, index) => (
            <Card key={index} className="group">
              <div className="mb-4">
                <motion.div
                  whileHover={{ rotate: 5, scale: 1.1 }}
                  className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-primary/10 text-primary"
                >
                  <feature.icon className="w-6 h-6" />
                </motion.div>
              </div>
              <h3 className="text-xl font-semibold mb-2 group-hover:text-primary transition-colors">
                {feature.title}
              </h3>
              <p className="text-muted-foreground text-sm leading-relaxed">
                {feature.description}
              </p>
            </Card>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
